### PR TITLE
rederr: fix license evaluation

### PR DESCRIPTION
**Pull request by Mic92**

### CODE REVIEW

**Comment by JohnAZoidberg** [comment]
Thanks! Is there an easy command/flag to nix-build for me to check that the meta attributes are correct?

**Comment by JohnAZoidberg** [comment]
Fixed here: 514132b

**Comment by Mic92** [comment]
A simplified version is:

```
nix-env -f . -qa \* --meta --xml --drv-path --show-trace >/dev/null
```

The real command to check is: https://github.com/nix-community/NUR/blob/master/nur/update.py#L32

but I agree there should be a simple command tool to check this.

**Comment by Mic92** [comment]
Also tracked here: https://github.com/nix-community/NUR/issues/53

**Pull request closed without merging**
